name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Run build
        run: pnpm run build

      - name: Validate build
        run: |
          if [ -d .next]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi

      - name: Deploy to build branch
        run: |
          git checkout -b build
          git add .
          git commit -m "Add build files"
          git push origin build
